package codewave

const introduction = `// This file is generated by pharosnet/dalg, please don't change it by hand. `

func waveIntroduction(w Writer) {
	w.WriteString(introduction)
	w.WriteString("\n")
}
